# Generated by Django 4.2.6 on 2023-11-28 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_alter_category_options_alter_contact_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='sow',
            field=models.BooleanField(default=True),
        ),
    ]
