# Generated by Django 4.2.6 on 2023-11-28 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0005_contact_sow'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='sow',
            new_name='show',
        ),
    ]
